#!/usr/bin/bash
gcc -Lwindows -Os -flto -ffunction-sections -Wl,--gc-sections -D__STDC_WANT_IEC_60559_BFP_EXT__ -o main.exe main.c -I /usr/include -L. -lraylib -lopengl32 -lgdi32 -lwinmm -lm -lregex -D_POSIX_C_SOURCE=200809L -w
strip main.exe
./main.exe
